# Specify taps (additional repositories)
tap "FelixKratz/formulae"

# Install Homebrew formulas (command-line utilities and libraries)
brew "git"
brew "node"
brew "nvm"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "stow"
brew "fzf"
brew "bat"
brew "fd"
brew "zoxide"
brew "lua"
brew "luajit"
brew "luarocks"
brew "prettier"
brew "make"
brew "ripgrep"
brew "git"
brew "lazygit"
brew "tmux"
brew "neovim"
brew "starship"
brew "tree-sitter"
brew "tree"
