return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = { "BufReadPost", "BufNewFile" },
	dependencies = { "nvim-treesitter/nvim-treesitter-textobjects" },
	config = function()
		require("nvim-treesitter.configs").setup({
			highlight = { enable = true },
			indent = { enable = true, disable = { "python" } },
			context_commentstring = { enable = true, enable_autocmd = false },
			move = { enable = true },
			select = { enable = true },
			ensure_installed = {
				"bash",
				"c",
				"cpp",
				"css",
				"csv",
				"diff",
				"dockerfile",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"go",
				"gomod",
				"gosum",
				"gowork",
				"gotmpl",
				"graphql",
				"html",
				"javascript",
				"jq",
				"jsdoc",
				"json",
				"lua",
				"luadoc",
				"markdown",
				"markdown_inline",
				"regex",
				"ruby",
				"sql",
				"ssh_config",
				"tmux",
				"toml",
				"tsx",
				"typescript",
				"typst",
				"vim",
				"yaml",
			},
			auto_install = true,
			sync_install = false,
			ignore_install = {},
			modules = {},
			incremental_selection = {
				enable = true,
				keymaps = {
                    init_selection = "<C-space>",
                    node_incremental = "<C-space>",
                    scope_incremental = false,
                    node_decremental = "<bs>",
                },
			},
            textobjects = {
                select = {
                    enable = true,
                    lookahead = true,
                    keymaps = {
                        -- existing
                        ["af"] = "@function.outer", ["if"] = "@function.inner",
                        ["ac"] = "@class.outer",    ["ic"] = "@class.inner",
                        ["am"] = "@module.outer",   ["im"] = "@module.inner",

                        -- NEW ▾
                        ["ab"] = "@block.outer",        ["ib"] = "@block.inner",
                        ["a?"] = "@conditional.outer",  ["i?"] = "@conditional.inner",
                        ["al"] = "@loop.outer",         ["il"] = "@loop.inner",
                        ["ap"] = "@parameter.outer",    ["ip"] = "@parameter.inner",
                        ["ar"] = "@regex.outer",        ["ir"] = "@regex.inner",
                        ["a/"] = "@comment.outer",      -- whole comment line
                    },
                },
            },
		})
	end,
}
