# vim:set ft=tmux:
%hidden MODULE_NAME='ctp_prayer_times'

set-option -gq "@catppuccin_${MODULE_NAME}_icon" '🕌'
set-option -gq "@catppuccin_${MODULE_NAME}_color" '#(/Users/yousefhadder/github/muslim-prayers/scripts/prayer_times.sh color)'
set-option -gq "@catppuccin_${MODULE_NAME}_text" '#(/Users/yousefhadder/github/muslim-prayers/scripts/prayer_times.sh status)'
set-option -gq "@catppuccin_status_${MODULE_NAME}_icon_bg" '#(/Users/yousefhadder/github/muslim-prayers/scripts/prayer_times.sh color)'

source-file -F '#{TMUX_PLUGIN_MANAGER_PATH}/tmux/utils/status_module.conf'
