name: Copilot README Update

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  create-copilot-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Copilot issue
        id: create_issue
        run: |
          ISSUE_URL=$(gh issue create \
            --title "🤖 Review latest commit and update README files if needed" \
            --body "Review the latest commit and update the README files (root README.md and neovim/.config/neovim/README.md) if the changes are worthy of being documented." \
            --label "copilot")
          echo "issue_url=$ISSUE_URL" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign Copilot to issue
        run: |
          ISSUE_NUMBER=$(echo "${{ steps.create_issue.outputs.issue_url }}" | grep -o '[0-9]*$')
          gh issue edit $ISSUE_NUMBER --add-assignee "@copilot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
