name: Copilot README Update

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'nvim/.config/nvim/README.md'
      - '.github/workflows/copilot-readme-update.yml'
  workflow_dispatch:

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  create-copilot-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Copilot issue
        id: create_issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_url=$(gh issue create \
            --title "🤖 Review latest commit and update README files if needed" \
            --body "Review the latest commit and update the README files (root README.md and nvim/.config/nvim/README.md) if the changes are worthy of being documented." \
            --label "copilot")
          echo "issue_url=$issue_url" >> "$GITHUB_OUTPUT"

      - name: Wait briefly before assigning
        run: sleep 5

      - name: Assign Copilot to issue (using user PAT so agent triggers)
        env:
          GH_TOKEN: ${{ secrets.COPILOT_ISSUE_ASSIGN }}
          ISSUE_URL: ${{ steps.create_issue.outputs.issue_url }}
        run: |
          issue_number=$(echo "$ISSUE_URL" | grep -o '[0-9]*$')
          echo "Assigning copilot to issue #$issue_number"
          gh issue edit "$issue_number" --add-assignee "@copilot"
          echo "Assigned."

      - name: Confirmation log
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ steps.create_issue.outputs.issue_url }}
        run: |
          issue_number=$(echo "$ISSUE_URL" | grep -o '[0-9]*$')
          gh issue view "$issue_number" --json number,title,assignees --jq '.'
